"""Shared function-word and stopword lists for keyword extraction.

Centralised here so that sparse_index, sparse_engine, knowledge/store,
and CLI prefill commands all use the same word lists.
"""

from __future__ import annotations

import re

# -----------------------------------------------------------------------
# Function words — stripped from keyword entries to save tokens
# -----------------------------------------------------------------------

FUNCTION_WORDS = frozenset(
    {
        "the",
        "a",
        "an",
        "is",
        "was",
        "are",
        "were",
        "be",
        "been",
        "being",
        "have",
        "has",
        "had",
        "do",
        "does",
        "did",
        "will",
        "would",
        "could",
        "should",
        "may",
        "might",
        "shall",
        "can",
        "to",
        "of",
        "in",
        "for",
        "on",
        "with",
        "at",
        "by",
        "from",
        "as",
        "into",
        "through",
        "during",
        "before",
        "after",
        "and",
        "but",
        "or",
        "nor",
        "not",
        "so",
        "yet",
        "both",
        "either",
        "neither",
        "each",
        "every",
        "all",
        "any",
        "few",
        "more",
        "most",
        "other",
        "some",
        "such",
        "no",
        "only",
        "own",
        "same",
        "than",
        "too",
        "very",
        "just",
        "that",
        "this",
        "these",
        "those",
        "it",
        "its",
        "he",
        "she",
        "they",
        "them",
        "his",
        "her",
        "their",
        "we",
        "you",
        "me",
        "him",
        "us",
        "my",
        "your",
        "our",
        "who",
        "what",
        "which",
        "when",
        "where",
        "how",
        "why",
        "about",
        "up",
        "out",
        "if",
        "then",
        # Contractions
        "s",
        "t",
        "re",
        "ve",
        "ll",
        "d",
        "m",
        "i",
    }
)

# Common abbreviations that appear everywhere and carry no information
COMMON_ABBREVIATIONS = frozenset(
    {
        "I",
        "OK",
        "AM",
        "PM",
        "US",
        "UK",
        "TV",
        "ID",
        "GO",
        "CC",
        "SC",
        "MS",
        "AN",
        "ON",
        "OR",
        "AT",
        "OF",
        "BY",
        "IF",
        "UP",
        "NO",
        "SO",
        "DO",
    }
)

# Regex for extracting word tokens
WORD_RE = re.compile(r"[a-zA-Z][a-zA-Z'-]*[a-zA-Z]|[a-zA-Z]")

# -----------------------------------------------------------------------
# Stopwords — broader set for content word extraction
# -----------------------------------------------------------------------

STOPWORDS = frozenset(
    {
        "the",
        "a",
        "an",
        "this",
        "that",
        "these",
        "those",
        "in",
        "of",
        "at",
        "to",
        "for",
        "with",
        "by",
        "on",
        "he",
        "she",
        "it",
        "they",
        "we",
        "you",
        "i",
        "me",
        "was",
        "were",
        "is",
        "are",
        "have",
        "had",
        "do",
        "did",
        "and",
        "or",
        "but",
        "so",
        "because",
        "if",
        "when",
        "very",
        "really",
        "just",
        "also",
        "then",
        "not",
        "no",
        "be",
        "been",
        "being",
        "has",
        "will",
        "would",
        "could",
        "should",
        "may",
        "might",
        "can",
        "shall",
        "must",
        "about",
        "from",
        "into",
        "through",
        "during",
        "before",
        "after",
        "above",
        "below",
        "between",
        "under",
        "over",
        "here",
        "there",
        "where",
        "how",
        "what",
        "which",
        "who",
        "all",
        "each",
        "every",
        "both",
        "few",
        "more",
        "most",
        "other",
        "some",
        "such",
        "only",
        "own",
        "same",
        "than",
        "too",
        "out",
        "up",
        "down",
        "off",
        "now",
        "get",
        "got",
        "go",
        "going",
        "went",
        "come",
        "came",
        "make",
        "made",
        "take",
        "took",
        "give",
        "gave",
        "say",
        "said",
        "tell",
        "told",
        "ask",
        "asked",
        "think",
        "thought",
        "know",
        "knew",
        "see",
        "saw",
        "want",
        "need",
        "like",
        "look",
        "looked",
        "well",
        "back",
        "way",
        "right",
        "good",
        "new",
        "roger",
        "copy",
        "okay",  # transcript-specific
    }
)


__all__ = ["COMMON_ABBREVIATIONS", "FUNCTION_WORDS", "STOPWORDS", "WORD_RE"]
